package com.mycompany.personal;

import java.sql.*;
import java.util.ArrayList;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
/**
 *
 * @author mehme
 */
public class demo extends javax.swing.JFrame {
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(demo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(demo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(demo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(demo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new demo().setVisible(true);
        });
    }
  
    DefaultTableModel model;
    public demo() {
        initComponents();
        populateTable();
      
    }
    public void populateTable(){
        
        model = (DefaultTableModel)tblPersonal.getModel();
        model.setRowCount(0);
        try {
            ArrayList<officeWorkers> workers = getWorkers();
            for(officeWorkers worker:workers){
                Object[]row ={  
                    worker.getIdOfficeWorkers(),
                    worker.getName(),
                    worker. getOfficeCode(),
                    worker.getWorkHours(),
                    worker.getInsurance()};
                model.addRow(row);
            }
        } catch (SQLException ex) {
           
        }
    }
    public ArrayList<officeWorkers> getWorkers ()throws SQLException{
        Connection connection=null;
        dbHelper dbHelper=new dbHelper ();
        Statement statement=null;
        ResultSet resultSet;
        ArrayList<officeWorkers> workers=null;
        try
        {
            connection=dbHelper.getConnection();
            statement=connection.createStatement();
            resultSet=statement.executeQuery("select * from officeWorkers");
            workers =new ArrayList<officeWorkers>();
            while (resultSet.next()){
                workers.add(new officeWorkers(
             resultSet.getInt("idOfficeWorkers"),
             resultSet.getString("Name"),
             resultSet.getString("OfficeCode"),
             resultSet.getInt("WorkHours"),
             resultSet.getString("Insurance")
                
                
                ));
            }
        }catch(SQLException exception){
            dbHelper.showErrorMessage(exception);
            
            
        }
        finally {
            statement.close();
            connection.close();
        }
        return workers;     
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblPersonal = new javax.swing.JTable();
        txtSearch = new javax.swing.JTextField();
        lblSearch = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        lblOfficeCode = new javax.swing.JLabel();
        lblwprkHours = new javax.swing.JLabel();
        lblInsurance = new javax.swing.JLabel();
        tbxName = new javax.swing.JTextField();
        tbxOfficeCode = new javax.swing.JTextField();
        tbxWorkHours = new javax.swing.JTextField();
        tbxInsurance = new javax.swing.JTextField();
        btnAdd = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tblPersonal.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "idOfficeWorkers", "Name", "OfficeCode", "WorkHours", "Insurance"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblPersonal);
        if (tblPersonal.getColumnModel().getColumnCount() > 0) {
            tblPersonal.getColumnModel().getColumn(0).setResizable(false);
            tblPersonal.getColumnModel().getColumn(1).setResizable(false);
            tblPersonal.getColumnModel().getColumn(2).setResizable(false);
            tblPersonal.getColumnModel().getColumn(3).setResizable(false);
            tblPersonal.getColumnModel().getColumn(4).setResizable(false);
        }

        txtSearch.setText(" ");
        txtSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSearchKeyReleased(evt);
            }
        });

        lblSearch.setText("Arama ifadesi");

        lblName.setText("Çalışan İsmi:");

        lblOfficeCode.setText("Office Code:");

        lblwprkHours.setText("WorkHours:");

        lblInsurance.setText("Insurance:");

        tbxName.setText(" ");

        tbxOfficeCode.setText(" ");

        tbxWorkHours.setText(" ");

        tbxInsurance.setText(" ");

        btnAdd.setText("EKLE");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 752, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtSearch))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(lblOfficeCode, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(tbxOfficeCode, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblName, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(41, 41, 41)
                                .addComponent(tbxName)))
                        .addGap(169, 169, 169)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblInsurance, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblwprkHours, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tbxWorkHours)
                            .addComponent(tbxInsurance)
                            .addComponent(btnAdd, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE))))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSearch)
                    .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblName)
                    .addComponent(lblwprkHours)
                    .addComponent(tbxName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tbxWorkHours, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblOfficeCode)
                    .addComponent(lblInsurance)
                    .addComponent(tbxOfficeCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tbxInsurance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(62, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchKeyReleased
        String searchKey=txtSearch.getText();
        TableRowSorter<DefaultTableModel> tableRowSorter=
                new TableRowSorter<DefaultTableModel>(model); 
        tblPersonal.setRowSorter(tableRowSorter);
        tableRowSorter.setRowFilter(RowFilter.regexFilter(searchKey));
        
    }//GEN-LAST:event_txtSearchKeyReleased

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        Connection connection=null;
        dbHelper dbHelper=new dbHelper ();
        PreparedStatement statement =null;
        try{
            connection =dbHelper.getConnection();
            String sql ="insert into officeWorkers (Name,OfficeCode,WorkHours,Insurance)values (?,?,?,?)";
            statement=connection.prepareStatement(sql);
            statement.setString(1,tbxName.getText());
            statement.setString(2,tbxOfficeCode.getText());
            statement.setInt(3,Integer.valueOf(tbxWorkHours.getText()));
            statement.setString(4,tbxInsurance.getText());
            int result=statement.executeUpdate();
            populateTable();
        }catch(SQLException exception){
            dbHelper.showErrorMessage(exception);
        }
        finally{
            try {
                statement.close();
                connection.close();
            } catch (SQLException ex) {
                
            }
        }
    }//GEN-LAST:event_btnAddActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblInsurance;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblOfficeCode;
    private javax.swing.JLabel lblSearch;
    private javax.swing.JLabel lblwprkHours;
    private javax.swing.JTable tblPersonal;
    private javax.swing.JTextField tbxInsurance;
    private javax.swing.JTextField tbxName;
    private javax.swing.JTextField tbxOfficeCode;
    private javax.swing.JTextField tbxWorkHours;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables
}
